// migrations/alterColumnDefault.ts

import { colors } from "../utils/logColors.js";
import { buildDefaultSQL } from "../sql/buildDefaultSQL.js";

/* ===================================================== */
/* HELPERS                                               */
/* ===================================================== */

function q(n: string) {
  return `"${n.replace(/"/g, '""')}"`;
}

/**
 * Normalize ANY Postgres default (model or DB)
 * into a canonical string so comparisons converge.
 */
function normalizeDefault(d: string | null | undefined): string | null {
  if (d == null) return null;

  let s = String(d).trim().toLowerCase();

  // unwrap ALL parentheses
  while (s.startsWith("(") && s.endsWith(")")) {
    s = s.slice(1, -1).trim();
  }

  // 🔑 KILL ALL CASTS — THIS IS THE FIX
  const castIdx = s.indexOf("::");
  if (castIdx !== -1) {
    s = s.slice(0, castIdx);
  }

  // normalize known functions
  if (s === "current_timestamp" || s === "current_timestamp()") {
    return "current_timestamp";
  }
  if (s === "gen_random_uuid()" || s === "gen_random_uuid") {
    return "gen_random_uuid";
  }

  // ARRAY[...] → {...}
  s = s.replace(/^array\s*\[(.*)\]$/i, "{$1}");

  // remove array literal quotes
  s = s.replace(/"/g, "");

  // remove string quotes
  s = s.replace(/'/g, "");

  // remove whitespace
  s = s.replace(/\s+/g, "");

  return s;
}

/* ===================================================== */
/* MAIN                                                  */
/* ===================================================== */

export async function alterColumnDefault({
  client,
  table,
  existing,
  processed,
  messages,
}: {
  client: any;
  table: string;
  existing: Map<string, any>;
  processed: any[];
  messages: string[];
}) {
  const alters: string[] = [];

  for (const col of processed) {
    // virtual columns never have defaults
    if (col.__virtual) continue;

    const row = existing.get(col.name);
    if (!row) continue;

    const modelSQL = buildDefaultSQL(col); // string | null
    const dbSQL = row.column_default; // string | null

    const nModel = normalizeDefault(modelSQL);
    const nDb = normalizeDefault(dbSQL);

    // already converged
    if (nModel === nDb) continue;

    /* ---------- DROP IDENTITY DEFAULT ---------- */
    if (!col.__identity && row.is_identity === "YES") {
      await client.query(`
        ALTER TABLE "${table}"
        ALTER COLUMN "${col.name}"
        DROP IDENTITY IF EXISTS
      `);
      messages.push(
        `${colors.success}Dropped IDENTITY:${colors.reset} ${colors.subject}${col.name}${colors.reset}`
      );
    }

    /* ---------- DROP DEFAULT ---------- */
    if (nModel == null && nDb != null) {
      alters.push(`ALTER COLUMN ${q(col.name)} DROP DEFAULT`);
      messages.push(
        `${colors.success}Dropped DEFAULT:${colors.reset} ${colors.subject}${col.name}${colors.reset}`
      );
      continue;
    }

    /* ---------- SET IDENTITY DEFAULT ---------- */
    if (col.__identity && row.is_identity !== "YES") {
      await client.query(`
        ALTER TABLE "${table}"
        ALTER COLUMN "${col.name}"
        ADD GENERATED BY DEFAULT AS IDENTITY
      `);

      messages.push(
        `${colors.success}Set IDENTITY:${colors.reset} ${colors.subject}${col.name}${colors.reset}`
      );
    }

    /* ---------- SET DEFAULT ---------- */
    if (nModel != null) {
      alters.push(`ALTER COLUMN ${q(col.name)} SET DEFAULT ${modelSQL}`);
      messages.push(
        `${colors.success}Set DEFAULT:${colors.reset} ${colors.subject}${col.name}${colors.reset}`
      );
    }
  }

  if (alters.length > 0) {
    await client.query(`ALTER TABLE ${q(table)} ${alters.join(", ")}`);
  }

  return { ok: true };
}
