// morm.generated.d.ts
// ⚠️  Auto-generated by MORM — do not edit manually
// Generated: 2026-05-16T12:29:05.887Z
// Add this file to .gitignore — never import it directly

export {};

declare global {

  type UserType = {
    id?: string | null;
    name?: string | null;
    account_number: number;
    class?: string | null;
    initials?: string;
    created_at?: Date;
    updated_at?: Date;
  }

  type ProfileType = {
    id?: string | null;
    fullname: string;
    profile_image?: string | null;
    created_at?: Date;
    updated_at?: Date;
  }

  type MormDB = {
    user: {
      create: (clause: import("./morm/query/index.js").CreateClause<UserType>) => Promise<UserType | UserType[] | { count: number }>;
      find: (clause?: import("./morm/query/index.js").FindClause<UserType>) => Promise<UserType[]>;
      findOne: (clause?: import("./morm/query/index.js").FindOneClause<UserType>) => Promise<UserType | null>;
      update: (clause: import("./morm/query/index.js").UpdateClause<UserType>) => Promise<{ count: number }>;
      delete: (clause: { where?: any }) => Promise<{ count: number }>;
    };
    profile: {
      create: (clause: import("./morm/query/index.js").CreateClause<ProfileType>) => Promise<ProfileType | ProfileType[] | { count: number }>;
      find: (clause?: import("./morm/query/index.js").FindClause<ProfileType>) => Promise<ProfileType[]>;
      findOne: (clause?: import("./morm/query/index.js").FindOneClause<ProfileType>) => Promise<ProfileType | null>;
      update: (clause: import("./morm/query/index.js").UpdateClause<ProfileType>) => Promise<{ count: number }>;
      delete: (clause: { where?: any }) => Promise<{ count: number }>;
    };
  }

  namespace Express {
    interface Request {
      db: import("./morm/morm.js").Morm;
    }
  }
}

declare module "./morm/morm.js" {
  interface Morm {
    user: {
      create: (clause: import("./morm/query/index.js").CreateClause<UserType>) => Promise<UserType | UserType[] | { count: number }>;
      find: (clause?: import("./morm/query/index.js").FindClause<UserType>) => Promise<UserType[]>;
      findOne: (clause?: import("./morm/query/index.js").FindOneClause<UserType>) => Promise<UserType | null>;
      update: (clause: import("./morm/query/index.js").UpdateClause<UserType>) => Promise<{ count: number }>;
      delete: (clause: { where?: any }) => Promise<{ count: number }>;
    };
    profile: {
      create: (clause: import("./morm/query/index.js").CreateClause<ProfileType>) => Promise<ProfileType | ProfileType[] | { count: number }>;
      find: (clause?: import("./morm/query/index.js").FindClause<ProfileType>) => Promise<ProfileType[]>;
      findOne: (clause?: import("./morm/query/index.js").FindOneClause<ProfileType>) => Promise<ProfileType | null>;
      update: (clause: import("./morm/query/index.js").UpdateClause<ProfileType>) => Promise<{ count: number }>;
      delete: (clause: { where?: any }) => Promise<{ count: number }>;
    };
    transaction: <T, TDb extends object = MormDB>(fn: (db: TDb) => Promise<T>) => Promise<T>;
  }
}