// morm.generated.d.ts
// ⚠️ ⚠️ ⚠️ Auto-generated by MORM; do not edit manually ⚠️ ⚠️ ⚠️
// Generated: 2026-05-19T17:32:54.803Z

export {};

declare global {

  type UserType = {
    id?: string | null;
    username?: string | null;
    email?: string | null;
    account_number?: number | null;
    initials?: string | null;
    state?: string | null;
    tags?: string[] | null;
    is_active?: boolean | null;
    role?: "ADMIN" | "SUPERADMIN" | "STAFF" | "MARKED" | string | null;
    created_at?: Date;
    updated_at?: Date;
  }

  type ProfileType = {
    id?: string | null;
    fullname: string;
    avatar?: string | null;
    user_id: string;
    created_at?: Date;
    updated_at?: Date;
  }

  type MormDB = {
    user: {
      create(clause: import("./morm/query/index.js").CreateClause<UserType> & { data: Partial<UserType>[]; include: any }): Promise<UserType[]>;
      create(clause: import("./morm/query/index.js").CreateClause<UserType> & { data: Partial<UserType>[]; exclude: any }): Promise<UserType[]>;
      create(clause: import("./morm/query/index.js").CreateClause<UserType> & { data: Partial<UserType>; include: any }): Promise<UserType>;
      create(clause: import("./morm/query/index.js").CreateClause<UserType> & { data: Partial<UserType>; exclude: any }): Promise<UserType>;
      create(clause: import("./morm/query/index.js").CreateClause<UserType>): Promise<{ count: number }>;
      find(clause: import("./morm/query/index.js").FindClause<UserType> & { count: true }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<UserType> & { sum: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<UserType> & { avg: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<UserType> & { min: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<UserType> & { max: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause?: import("./morm/query/index.js").FindClause<UserType>): Promise<UserType[]>;
      findOne: (clause?: import("./morm/query/index.js").FindOneClause<UserType>) => Promise<UserType | null>;
      update: (clause: import("./morm/query/index.js").UpdateClause<UserType>) => Promise<{ count: number }>;
      delete: (clause: { where?: any }) => Promise<{ count: number }>;
    };
    profile: {
      create(clause: import("./morm/query/index.js").CreateClause<ProfileType> & { data: Partial<ProfileType>[]; include: any }): Promise<ProfileType[]>;
      create(clause: import("./morm/query/index.js").CreateClause<ProfileType> & { data: Partial<ProfileType>[]; exclude: any }): Promise<ProfileType[]>;
      create(clause: import("./morm/query/index.js").CreateClause<ProfileType> & { data: Partial<ProfileType>; include: any }): Promise<ProfileType>;
      create(clause: import("./morm/query/index.js").CreateClause<ProfileType> & { data: Partial<ProfileType>; exclude: any }): Promise<ProfileType>;
      create(clause: import("./morm/query/index.js").CreateClause<ProfileType>): Promise<{ count: number }>;
      find(clause: import("./morm/query/index.js").FindClause<ProfileType> & { count: true }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<ProfileType> & { sum: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<ProfileType> & { avg: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<ProfileType> & { min: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<ProfileType> & { max: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause?: import("./morm/query/index.js").FindClause<ProfileType>): Promise<ProfileType[]>;
      findOne: (clause?: import("./morm/query/index.js").FindOneClause<ProfileType>) => Promise<ProfileType | null>;
      update: (clause: import("./morm/query/index.js").UpdateClause<ProfileType>) => Promise<{ count: number }>;
      delete: (clause: { where?: any }) => Promise<{ count: number }>;
    };
  }

  namespace Express {
    interface Request {
      db: import("./morm/morm.js").Morm;
    }
  }
}

declare module "./morm/morm.js" {
  interface Morm {
    user: {
      create(clause: import("./morm/query/index.js").CreateClause<UserType> & { data: Partial<UserType>[]; include: any }): Promise<UserType[]>;
      create(clause: import("./morm/query/index.js").CreateClause<UserType> & { data: Partial<UserType>[]; exclude: any }): Promise<UserType[]>;
      create(clause: import("./morm/query/index.js").CreateClause<UserType> & { data: Partial<UserType>; include: any }): Promise<UserType>;
      create(clause: import("./morm/query/index.js").CreateClause<UserType> & { data: Partial<UserType>; exclude: any }): Promise<UserType>;
      create(clause: import("./morm/query/index.js").CreateClause<UserType>): Promise<{ count: number }>;
      find(clause: import("./morm/query/index.js").FindClause<UserType> & { count: true }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<UserType> & { sum: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<UserType> & { avg: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<UserType> & { min: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<UserType> & { max: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause?: import("./morm/query/index.js").FindClause<UserType>): Promise<UserType[]>;
      findOne: (clause?: import("./morm/query/index.js").FindOneClause<UserType>) => Promise<UserType | null>;
      update: (clause: import("./morm/query/index.js").UpdateClause<UserType>) => Promise<{ count: number }>;
      delete: (clause: { where?: any }) => Promise<{ count: number }>;
    };
    profile: {
      create(clause: import("./morm/query/index.js").CreateClause<ProfileType> & { data: Partial<ProfileType>[]; include: any }): Promise<ProfileType[]>;
      create(clause: import("./morm/query/index.js").CreateClause<ProfileType> & { data: Partial<ProfileType>[]; exclude: any }): Promise<ProfileType[]>;
      create(clause: import("./morm/query/index.js").CreateClause<ProfileType> & { data: Partial<ProfileType>; include: any }): Promise<ProfileType>;
      create(clause: import("./morm/query/index.js").CreateClause<ProfileType> & { data: Partial<ProfileType>; exclude: any }): Promise<ProfileType>;
      create(clause: import("./morm/query/index.js").CreateClause<ProfileType>): Promise<{ count: number }>;
      find(clause: import("./morm/query/index.js").FindClause<ProfileType> & { count: true }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<ProfileType> & { sum: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<ProfileType> & { avg: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<ProfileType> & { min: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause: import("./morm/query/index.js").FindClause<ProfileType> & { max: string }): Promise<import("./morm/query/index.js").AggregationResult>;
      find(clause?: import("./morm/query/index.js").FindClause<ProfileType>): Promise<ProfileType[]>;
      findOne: (clause?: import("./morm/query/index.js").FindOneClause<ProfileType>) => Promise<ProfileType | null>;
      update: (clause: import("./morm/query/index.js").UpdateClause<ProfileType>) => Promise<{ count: number }>;
      delete: (clause: { where?: any }) => Promise<{ count: number }>;
    };
    transaction: <T, TDb extends object = MormDB>(fn: (db: TDb) => Promise<T>) => Promise<T>;
  }
}