// morm.generated.d.ts
// ⚠️ ⚠️ ⚠️ Auto-generated by MORM; do not edit manually ⚠️ ⚠️ ⚠️
// Generated: 2026-05-20T19:06:06.722Z

export {};

declare global {

  type UserType = {
    id?: string | null;
    username?: string | null;
    email?: string | null;
    account_number?: number | string | null;
    initials?: string | null;
    state?: string | null;
    tags?: string[] | null;
    is_active?: boolean | null;
    role?: "ADMIN" | "SUPERADMIN" | "STAFF" | "MARKED" | null;
    count?: (number | string)[] | null;
    ids?: string[] | null;
    dates?: Date[] | null;
    count_?: (number | string)[] | null;
    countnum_?: boolean[] | null;
    ids_?: string[] | null;
    dates_?: Date[] | null;
    boolean?: boolean[] | null;
    datestz_?: Date[] | null;
    time?: string[] | null;
    created_at?: Date;
    updated_at?: Date;
  }

  type UserInputType = {
    id?: string | null;
    username?: string | null;
    email?: string | null;
    account_number?: number | string | null;
    initials?: string | null;
    state?: string | null;
    tags?: string[] | null;
    is_active?: boolean | null;
    role?: "ADMIN" | "SUPERADMIN" | "STAFF" | "MARKED" | (string & {}) | null;
    count?: (number | string)[] | null;
    ids?: string[] | null;
    dates?: (Date | string)[] | null;
    count_?: (number | string)[] | null;
    countnum_?: boolean[] | null;
    ids_?: string[] | null;
    dates_?: (Date | string)[] | null;
    boolean?: boolean[] | null;
    datestz_?: (Date | string)[] | null;
    time?: string[] | null;
    created_at?: Date | string;
    updated_at?: Date | string;
  }

  type ProfileType = {
    id?: string | null;
    fullname: string;
    avatar?: string | null;
    user_id: string;
    time?: (number | string)[] | null;
    created_at?: Date;
    updated_at?: Date;
  }

  type ProfileInputType = {
    id?: string | null;
    fullname: string;
    avatar?: string | null;
    user_id: string;
    time?: (number | string)[] | null;
    created_at?: Date | string;
    updated_at?: Date | string;
  }

  type MormDB = {
    user: {
      create<C extends import("./morm/query/index.js").CreateClause<UserInputType>>(clause: C & { data: import("./morm/query/index.js").MaybeFunctionPartial<UserInputType>[] }): Promise<C extends { include: any } | { exclude: any } ? import("./morm/query/index.js").ProjectResult<UserType, C>[] : { count: number }>;
      create<C extends import("./morm/query/index.js").CreateClause<UserInputType>>(clause: C & { data: import("./morm/query/index.js").MaybeFunctionPartial<UserInputType> }): Promise<C extends { include: any } | { exclude: any } ? import("./morm/query/index.js").ProjectResult<UserType, C> : { count: number }>;
      find<C extends import("./morm/query/index.js").FindClause<UserType>>(clause?: C): Promise<import("./morm/query/index.js").FindResult<UserType, C>>;
      findOne: (clause?: import("./morm/query/index.js").FindOneClause<UserType>) => Promise<UserType | null>;
      update: (clause: import("./morm/query/index.js").UpdateClause<UserType>) => Promise<{ count: number }>;
      delete: (clause: { where?: any }) => Promise<{ count: number }>;
    };
    profile: {
      create<C extends import("./morm/query/index.js").CreateClause<ProfileInputType>>(clause: C & { data: import("./morm/query/index.js").MaybeFunctionPartial<ProfileInputType>[] }): Promise<C extends { include: any } | { exclude: any } ? import("./morm/query/index.js").ProjectResult<ProfileType, C>[] : { count: number }>;
      create<C extends import("./morm/query/index.js").CreateClause<ProfileInputType>>(clause: C & { data: import("./morm/query/index.js").MaybeFunctionPartial<ProfileInputType> }): Promise<C extends { include: any } | { exclude: any } ? import("./morm/query/index.js").ProjectResult<ProfileType, C> : { count: number }>;
      find<C extends import("./morm/query/index.js").FindClause<ProfileType>>(clause?: C): Promise<import("./morm/query/index.js").FindResult<ProfileType, C>>;
      findOne: (clause?: import("./morm/query/index.js").FindOneClause<ProfileType>) => Promise<ProfileType | null>;
      update: (clause: import("./morm/query/index.js").UpdateClause<ProfileType>) => Promise<{ count: number }>;
      delete: (clause: { where?: any }) => Promise<{ count: number }>;
    };
  }

  namespace Express {
    interface Request {
      db: import("./morm/morm.js").Morm;
    }
  }
}

declare module "./morm/morm.js" {
  interface Morm {
    user: {
      create<C extends import("./morm/query/index.js").CreateClause<UserInputType>>(clause: C & { data: import("./morm/query/index.js").MaybeFunctionPartial<UserInputType>[] }): Promise<C extends { include: any } | { exclude: any } ? import("./morm/query/index.js").ProjectResult<UserType, C>[] : { count: number }>;
      create<C extends import("./morm/query/index.js").CreateClause<UserInputType>>(clause: C & { data: import("./morm/query/index.js").MaybeFunctionPartial<UserInputType> }): Promise<C extends { include: any } | { exclude: any } ? import("./morm/query/index.js").ProjectResult<UserType, C> : { count: number }>;
      find<C extends import("./morm/query/index.js").FindClause<UserType>>(clause?: C): Promise<import("./morm/query/index.js").FindResult<UserType, C>>;
      findOne: (clause?: import("./morm/query/index.js").FindOneClause<UserType>) => Promise<UserType | null>;
      update: (clause: import("./morm/query/index.js").UpdateClause<UserType>) => Promise<{ count: number }>;
      delete: (clause: { where?: any }) => Promise<{ count: number }>;
    };
    profile: {
      create<C extends import("./morm/query/index.js").CreateClause<ProfileInputType>>(clause: C & { data: import("./morm/query/index.js").MaybeFunctionPartial<ProfileInputType>[] }): Promise<C extends { include: any } | { exclude: any } ? import("./morm/query/index.js").ProjectResult<ProfileType, C>[] : { count: number }>;
      create<C extends import("./morm/query/index.js").CreateClause<ProfileInputType>>(clause: C & { data: import("./morm/query/index.js").MaybeFunctionPartial<ProfileInputType> }): Promise<C extends { include: any } | { exclude: any } ? import("./morm/query/index.js").ProjectResult<ProfileType, C> : { count: number }>;
      find<C extends import("./morm/query/index.js").FindClause<ProfileType>>(clause?: C): Promise<import("./morm/query/index.js").FindResult<ProfileType, C>>;
      findOne: (clause?: import("./morm/query/index.js").FindOneClause<ProfileType>) => Promise<ProfileType | null>;
      update: (clause: import("./morm/query/index.js").UpdateClause<ProfileType>) => Promise<{ count: number }>;
      delete: (clause: { where?: any }) => Promise<{ count: number }>;
    };
    transaction: <T, TDb extends object = MormDB>(fn: (db: TDb) => Promise<T>) => Promise<T>;
  }
}